id: I884C33F8
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T12:54:25+00:00'
last_modified: '2022-06-08T06:45:24.103206+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN5568
  title: གསུང་ངག་ལམ་འབྲས་ཀྱི་ཆོས་འབྱུང་དང་ཁོག་ཕུག་ཉིས་སྦྲགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '9100':
      image_group_id: I3CN5570
      title: ''
      total_pages: 220
      order: 1
      base_file: 9100.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
