id: P006698
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN5568
  title: གསུང་ངག་ལམ་འབྲས་ཀྱི་ཆོས་འབྱུང་དང་ཁོག་ཕུག་ཉིས་སྦྲགས།
  author: ''
  volumes:
    0e357011b21348e6b2679a907e7e9275:
      image_group_id: I3CN5570
      title: ''
      volume_number: 1
      total_pages: 220
